// packages/solid/src/Askable.tsx
import type { ParentComponent, JSX } from 'solid-js';
import { splitProps } from 'solid-js';
import { Dynamic } from 'solid-js/web';

export interface AskableProps {
  meta: Record<string, unknown> | string;
  scope?: string;
  as?: string;
  [key: string]: unknown;
}

/**
 * Wrap any element to annotate it with structured data for AI assistants.
 *
 * @example
 * ```tsx
 * <Askable meta={{ metric: 'revenue', value: '$2.3M' }}>
 *   <div>Revenue: $2.3M</div>
 * </Askable>
 * ```
 */
export const Askable: ParentComponent<AskableProps> = (rawProps) => {
  const [local, rest] = splitProps(rawProps, ['meta', 'scope', 'as', 'children']);

  const metaStr = () =>
    typeof local.meta === 'string' ? local.meta : JSON.stringify(local.meta);

  return (
    <Dynamic
      component={local.as ?? 'div'}
      data-askable={metaStr()}
      data-askable-scope={local.scope}
      {...(rest as JSX.HTMLAttributes<HTMLElement>)}
    >
      {local.children}
    </Dynamic>
  );
};

// packages/qwik/src/Askable.tsx
import { component$, Slot, type JSXChildren } from '@builder.io/qwik';

export interface AskableProps {
  meta: string | Record<string, unknown>;
  scope?: string;
  as?: string;
  class?: string;
  style?: Record<string, string> | string;
  [key: string]: unknown;
}

/**
 * Renders a DOM element annotated with `data-askable` and optionally
 * `data-askable-scope`. Wrap any content the AI should be aware of.
 *
 * ```tsx
 * <Askable meta={{ metric: 'revenue', value: '$2.4M' }} scope="kpis">
 *   <article>$2.4M</article>
 * </Askable>
 * ```
 */
export const Askable = component$<AskableProps>((props) => {
  const { meta, scope, as: Tag = 'div', ...rest } = props;
  const metaStr = typeof meta === 'string' ? meta : JSON.stringify(meta);

  // Qwik doesn't support dynamic tag names via JSX variable — use a div wrapper trick
  return (
    <div
      data-askable={metaStr}
      data-askable-scope={scope}
      {...rest}
    >
      <Slot />
    </div>
  );
});
