// packages/solid/src/useAskableMultistepSource.ts
import { createSignal } from 'solid-js';
import { createAskableMultistepSource, buildMultistepSnapshot } from '@askable-ui/core';
import type {
  AskableCreateMultistepSourceOptions,
  AskableMultistepStep,
  AskableMultistepSourceSnapshot,
} from '@askable-ui/core';
import { useAskableSource, type UseAskableSourceOptions, type UseAskableSourceResult } from './useAskableSource.js';

export type { AskableMultistepStep, AskableMultistepSourceSnapshot };

export interface UseAskableMultistepSourceOptions
  extends UseAskableSourceOptions,
    Omit<AskableCreateMultistepSourceOptions, 'getSnapshot'> {
  /** Source registration id. Defaults to "multistep". */
  id?: string;
  /** Initial step definitions. */
  steps?: Pick<AskableMultistepStep, 'id' | 'label' | 'description' | 'optional'>[];
  /** Index of the initially active step. @default 0 */
  initialStep?: number;
}

export interface UseAskableMultistepSourceResult extends UseAskableSourceResult {
  snapshot: () => AskableMultistepSourceSnapshot | null;
  next: () => void;
  prev: () => void;
  goTo: (index: number) => void;
  complete: () => void;
  setError: (error: string | null) => void;
  reset: () => void;
}

/**
 * SolidJS primitive that tracks wizard and stepper flow state and exposes it
 * to AI assistants so they can guide users through multi-step processes.
 *
 * @example
 * ```tsx
 * const { snapshot, next } = useAskableMultistepSource({
 *   steps: [{ id: 'info', label: 'Info' }, { id: 'payment', label: 'Payment' }],
 * });
 * ```
 */
export function useAskableMultistepSource(
  options: UseAskableMultistepSourceOptions = {},
): UseAskableMultistepSourceResult {
  const { id = 'multistep', steps: initialStepDefs = [], initialStep = 0, describe, kind, enabled, ctx, name, events } = options;

  let startedAt = new Date().toISOString();

  const makeInitialSteps = (): AskableMultistepStep[] =>
    initialStepDefs.map((s, i) => ({ ...s, completed: false, active: i === initialStep, error: null }));

  const [snapshot, setSnapshot] = createSignal<AskableMultistepSourceSnapshot | null>(
    buildMultistepSnapshot(makeInitialSteps(), { startedAt }),
  );

  const source = createAskableMultistepSource({ describe, kind, getSnapshot: snapshot });
  const result = useAskableSource(id, source, { enabled, ctx, name, events });

  function updateSteps(updater: (steps: AskableMultistepStep[]) => AskableMultistepStep[]): void {
    setSnapshot((prev) => {
      if (!prev) return prev;
      return buildMultistepSnapshot(updater([...prev.steps]), { startedAt: prev.startedAt });
    });
    result.notifyChanged();
  }

  function next(): void {
    updateSteps((steps) => {
      const idx = steps.findIndex((s) => s.active);
      if (idx < 0 || idx >= steps.length - 1) return steps;
      steps[idx] = { ...steps[idx], active: false };
      steps[idx + 1] = { ...steps[idx + 1], active: true };
      return steps;
    });
  }

  function prev(): void {
    updateSteps((steps) => {
      const idx = steps.findIndex((s) => s.active);
      if (idx <= 0) return steps;
      steps[idx] = { ...steps[idx], active: false };
      steps[idx - 1] = { ...steps[idx - 1], active: true };
      return steps;
    });
  }

  function goTo(index: number): void {
    updateSteps((steps) => steps.map((s, i) => ({ ...s, active: i === index })));
  }

  function complete(): void {
    updateSteps((steps) => {
      const idx = steps.findIndex((s) => s.active);
      if (idx < 0) return steps;
      steps[idx] = { ...steps[idx], completed: true, active: false, error: null };
      if (idx < steps.length - 1) steps[idx + 1] = { ...steps[idx + 1], active: true };
      return steps;
    });
  }

  function setError(error: string | null): void {
    updateSteps((steps) => {
      const idx = steps.findIndex((s) => s.active);
      if (idx < 0) return steps;
      steps[idx] = { ...steps[idx], error };
      return steps;
    });
  }

  function reset(): void {
    startedAt = new Date().toISOString();
    setSnapshot(buildMultistepSnapshot(makeInitialSteps(), { startedAt }));
    result.notifyChanged();
  }

  return { ...result, snapshot, next, prev, goTo, complete, setError, reset };
}

// packages/qwik/src/useAskableMultistepSource.ts
import { useSignal } from '@builder.io/qwik';
import { createAskableMultistepSource, buildMultistepSnapshot } from '@askable-ui/core';
import type {
  AskableCreateMultistepSourceOptions,
  AskableMultistepStep,
  AskableMultistepSourceSnapshot,
} from '@askable-ui/core';
import { useAskableSource, type UseAskableSourceOptions, type UseAskableSourceResult } from './useAskableSource.js';

export type { AskableMultistepStep, AskableMultistepSourceSnapshot };

export interface UseAskableMultistepSourceOptions
  extends UseAskableSourceOptions,
    Omit<AskableCreateMultistepSourceOptions, 'getSnapshot'> {
  id?: string;
  steps?: Pick<AskableMultistepStep, 'id' | 'label' | 'description' | 'optional'>[];
  initialStep?: number;
}

export interface UseAskableMultistepSourceResult extends UseAskableSourceResult {
  snapshot: ReturnType<typeof useSignal<AskableMultistepSourceSnapshot | null>>;
  next(): void;
  prev(): void;
  goTo(indexOrId: number | string): void;
  setSteps(steps: Pick<AskableMultistepStep, 'id' | 'label' | 'description' | 'optional'>[]): void;
}

/**
 * Qwik hook that tracks wizard / stepper / checkout flow progress and exposes
 * it to AI assistants.
 *
 * ```tsx
 * export const Checkout = component$(() => {
 *   const wizard = useAskableMultistepSource({
 *     steps: [
 *       { id: 'cart', label: 'Cart' },
 *       { id: 'shipping', label: 'Shipping' },
 *       { id: 'payment', label: 'Payment' },
 *     ],
 *   });
 *   return (
 *     <div>
 *       <p>Step {wizard.snapshot.value?.currentIndex + 1}</p>
 *       <button onClick$={() => wizard.next()}>Next</button>
 *     </div>
 *   );
 * });
 * ```
 */
export function useAskableMultistepSource(options: UseAskableMultistepSourceOptions = {}): UseAskableMultistepSourceResult {
  const { id = 'multistep', steps: initialSteps = [], initialStep = 0, describe, kind, enabled, ctx, name, events } = options;

  const fullSteps: AskableMultistepStep[] = initialSteps.map((s, i) => ({
    ...s,
    index: i,
    isComplete: false,
    isActive: i === initialStep,
    isCurrent: i === initialStep,
  }));

  const snapshot = useSignal<AskableMultistepSourceSnapshot | null>(
    fullSteps.length > 0 ? buildMultistepSnapshot(fullSteps, initialStep, new Date().toISOString()) : null,
  );

  const source = createAskableMultistepSource({ describe, kind, getSnapshot: () => snapshot.value });
  const result = useAskableSource(id, source, { enabled, ctx, name, events });

  function currentSteps(): AskableMultistepStep[] {
    return snapshot.value?.steps ?? fullSteps;
  }

  function currentIndex(): number {
    return snapshot.value?.currentIndex ?? initialStep;
  }

  function applyIndex(idx: number): void {
    const steps = currentSteps();
    if (idx < 0 || idx >= steps.length) return;
    snapshot.value = buildMultistepSnapshot(steps, idx, new Date().toISOString());
    result.notifyChanged();
  }

  function next(): void { applyIndex(currentIndex() + 1); }
  function prev(): void { applyIndex(currentIndex() - 1); }

  function goTo(indexOrId: number | string): void {
    if (typeof indexOrId === 'number') { applyIndex(indexOrId); return; }
    const idx = currentSteps().findIndex((s) => s.id === indexOrId);
    if (idx >= 0) applyIndex(idx);
  }

  function setSteps(steps: Pick<AskableMultistepStep, 'id' | 'label' | 'description' | 'optional'>[]): void {
    const full: AskableMultistepStep[] = steps.map((s, i) => ({
      ...s,
      index: i,
      isComplete: false,
      isActive: i === 0,
      isCurrent: i === 0,
    }));
    snapshot.value = buildMultistepSnapshot(full, 0, new Date().toISOString());
    result.notifyChanged();
  }

  return { ...result, snapshot, next, prev, goTo, setSteps };
}
