// packages/solid/src/useAskableNotificationSource.ts
import { createEffect } from 'solid-js';
import { createAskableNotificationSource } from '@askable-ui/core';
import type {
  AskableCreateNotificationSourceOptions,
  AskableNotification,
  AskableNotificationSeverity,
} from '@askable-ui/core';
import { useAskableSource, type UseAskableSourceOptions, type UseAskableSourceResult } from './useAskableSource.js';

export type { AskableNotification, AskableNotificationSeverity };

export interface UseAskableNotificationSourceOptions
  extends UseAskableSourceOptions,
    Omit<AskableCreateNotificationSourceOptions, 'getNotifications'> {
  /** Source registration id. Defaults to "notifications". */
  id?: string;
  /**
   * Accessor returning the current notifications array.
   * The hook tracks this accessor and auto-notifies on change.
   */
  notifications?: () => readonly AskableNotification[];
}

export type UseAskableNotificationSourceResult = UseAskableSourceResult;

/**
 * SolidJS primitive that registers a notification context source.
 *
 * @example
 * ```tsx
 * const [toasts, setToasts] = createSignal<AskableNotification[]>([]);
 * useAskableNotificationSource({ notifications: toasts });
 * ```
 */
export function useAskableNotificationSource(
  options: UseAskableNotificationSourceOptions = {},
): UseAskableNotificationSourceResult {
  const {
    id = 'notifications',
    notifications,
    maxNotifications,
    describe,
    kind,
    enabled,
    ctx,
    name,
    events,
  } = options;

  const source = createAskableNotificationSource({
    getNotifications: () => notifications?.() ?? [],
    maxNotifications,
    describe,
    kind,
  });

  const result = useAskableSource(id, source, { enabled, ctx, name, events });

  if (notifications) {
    createEffect(() => {
      notifications();
      result.notifyChanged();
    });
  }

  return result;
}

// packages/qwik/src/useAskableNotificationSource.ts
import { useSignal } from '@builder.io/qwik';
import { createAskableNotificationSource } from '@askable-ui/core';
import type {
  AskableCreateNotificationSourceOptions,
  AskableNotification,
  AskableNotificationSeverity,
} from '@askable-ui/core';
import { useAskableSource, type UseAskableSourceOptions, type UseAskableSourceResult } from './useAskableSource.js';

export type { AskableNotification, AskableNotificationSeverity };

export interface UseAskableNotificationSourceOptions
  extends UseAskableSourceOptions,
    Pick<AskableCreateNotificationSourceOptions, 'describe' | 'kind'> {
  id?: string;
  maxEntries?: number;
}

export interface UseAskableNotificationSourceResult extends UseAskableSourceResult {
  notifications: ReturnType<typeof useSignal<AskableNotification[]>>;
  push(notification: Omit<AskableNotification, 'id' | 'timestamp'>): void;
  dismiss(id: string): void;
  clear(): void;
}

/**
 * Registers a notification source that tracks active toasts, alerts, and
 * banners so the AI can reference them.
 *
 * ```tsx
 * const { push, dismiss } = useAskableNotificationSource();
 * push({ message: 'Order placed!', severity: 'success' });
 * ```
 */
export function useAskableNotificationSource(
  options: UseAskableNotificationSourceOptions = {},
): UseAskableNotificationSourceResult {
  const { id = 'notifications', enabled, ctx, name, events, maxEntries = 20, describe, kind } = options;

  const notifications = useSignal<AskableNotification[]>([]);
  let nextId = 1;

  const source = createAskableNotificationSource({
    describe,
    kind,
    getNotifications: () => notifications.value,
  });
  const result = useAskableSource(id, source, { enabled, ctx, name, events });

  function push(notification: Omit<AskableNotification, 'id' | 'timestamp'>): void {
    const entry: AskableNotification = {
      ...notification,
      id: String(nextId++),
      timestamp: new Date().toISOString(),
    };
    const next = [entry, ...notifications.value];
    notifications.value = next.length > maxEntries ? next.slice(0, maxEntries) : next;
    result.notifyChanged();
  }

  function dismiss(id: string): void {
    notifications.value = notifications.value.filter((n) => n.id !== id);
    result.notifyChanged();
  }

  function clear(): void {
    notifications.value = [];
    result.notifyChanged();
  }

  return { ...result, notifications, push, dismiss, clear };
}
