// packages/solid/src/useAskableAgent.ts
import { createSignal } from 'solid-js';
import type {
  AskableAgentRequest,
  AskableAgentRequestOptions,
  AskableContext,
} from '@askable-ui/core';
import { useAskable, type UseAskableOptions } from './useAskable.js';

export type AskableAgentStatus = 'idle' | 'pending' | 'success' | 'error';

export interface UseAskableAgentOptions extends UseAskableOptions {
  onRequest?: (request: AskableAgentRequest) => AskableAgentRequest | void | undefined;
  onSuccess?: (response: unknown, request: AskableAgentRequest) => void;
  onError?: (error: unknown, request: AskableAgentRequest) => void;
  requestOptions?: AskableAgentRequestOptions;
  ctx?: AskableContext;
}

export interface UseAskableAgentResult<T = unknown> {
  send: (
    question: string,
    handler: (request: AskableAgentRequest) => T | Promise<T>,
  ) => Promise<T | undefined>;
  status: () => AskableAgentStatus;
  data: () => T | null;
  error: () => unknown;
  lastRequest: () => AskableAgentRequest | null;
  isLoading: () => boolean;
  reset: () => void;
  ctx: AskableContext;
}

/**
 * SolidJS primitive that packages the current UI context into an agent
 * request payload and hands it to your send handler.
 *
 * ```tsx
 * const { send, isLoading } = useAskableAgent();
 *
 * <button disabled={isLoading()} onClick={() =>
 *   send('What is this?', async (req) =>
 *     fetch('/api/chat', { method: 'POST', body: JSON.stringify(req) })
 *   )
 * }>
 *   {isLoading() ? 'Thinking…' : 'Ask AI'}
 * </button>
 * ```
 */
export function useAskableAgent<T = unknown>(
  options: UseAskableAgentOptions = {},
): UseAskableAgentResult<T> {
  const { onRequest, onSuccess, onError, requestOptions, ...askableOptions } = options;
  const { ctx } = useAskable(askableOptions);

  const [status, setStatus] = createSignal<AskableAgentStatus>('idle');
  const [data, setData] = createSignal<T | null>(null);
  const [error, setError] = createSignal<unknown>(null);
  const [lastRequest, setLastRequest] = createSignal<AskableAgentRequest | null>(null);

  async function send(
    question: string,
    handler: (request: AskableAgentRequest) => T | Promise<T>,
  ): Promise<T | undefined> {
    setStatus('pending');
    setError(null);

    let request = await ctx.toAgentRequest(question, requestOptions);
    if (onRequest) {
      const modified = onRequest(request);
      if (modified != null) request = modified;
    }
    setLastRequest(request);

    try {
      const result = await handler(request);
      setData(() => result);
      setStatus('success');
      onSuccess?.(result, request);
      return result;
    } catch (err) {
      setError(err);
      setStatus('error');
      onError?.(err, request);
      return undefined;
    }
  }

  function reset() {
    setStatus('idle');
    setData(null);
    setError(null);
    setLastRequest(null);
  }

  return {
    send,
    status,
    data,
    error,
    lastRequest,
    isLoading: () => status() === 'pending',
    reset,
    ctx,
  };
}

// packages/qwik/src/useAskableAgent.ts
import { useSignal, $ } from '@builder.io/qwik';
import type {
  AskableAgentRequest,
  AskableAgentRequestOptions,
  AskableContext,
} from '@askable-ui/core';
import { useAskable, type UseAskableOptions } from './useAskable.js';

export type AskableAgentStatus = 'idle' | 'pending' | 'success' | 'error';

export interface UseAskableAgentOptions extends UseAskableOptions {
  requestOptions?: AskableAgentRequestOptions;
}

export interface UseAskableAgentResult<T = unknown> {
  status: ReturnType<typeof useSignal<AskableAgentStatus>>;
  data: ReturnType<typeof useSignal<T | null>>;
  error: ReturnType<typeof useSignal<unknown>>;
  isLoading: ReturnType<typeof useSignal<boolean>>;
  lastRequest: ReturnType<typeof useSignal<AskableAgentRequest | null>>;
  send: (question: string, handler: (request: AskableAgentRequest) => T | Promise<T>) => Promise<T | undefined>;
  reset: () => void;
  ctx: AskableContext;
}

/**
 * Qwik hook that packages the current UI context into an agent request
 * and hands it to your send handler.
 *
 * @example
 * ```tsx
 * import { component$ } from '@builder.io/qwik';
 * import { useAskableAgent } from '@askable-ui/qwik';
 *
 * export const AskButton = component$(() => {
 *   const { send, isLoading } = useAskableAgent();
 *
 *   return (
 *     <button disabled={isLoading.value} onClick$={$(() =>
 *       send('What is this?', async (req) =>
 *         fetch('/api/ai', { method: 'POST', body: JSON.stringify(req) }).then(r => r.json())
 *       )
 *     )}>
 *       {isLoading.value ? 'Thinking…' : 'Ask AI'}
 *     </button>
 *   );
 * });
 * ```
 */
export function useAskableAgent<T = unknown>(
  options?: UseAskableAgentOptions,
): UseAskableAgentResult<T> {
  const status = useSignal<AskableAgentStatus>('idle');
  const data = useSignal<T | null>(null);
  const error = useSignal<unknown>(null);
  const isLoading = useSignal<boolean>(false);
  const lastRequest = useSignal<AskableAgentRequest | null>(null);

  const { requestOptions, ...askableOptions } = options ?? {};
  const { ctxRef } = useAskable(askableOptions);

  const send = $(async (
    question: string,
    handler: (request: AskableAgentRequest) => T | Promise<T>,
  ): Promise<T | undefined> => {
    const ctx = ctxRef.value;
    if (!ctx) return undefined;

    status.value = 'pending';
    isLoading.value = true;
    error.value = null;

    const request = await ctx.toAgentRequest(question, requestOptions);
    lastRequest.value = request;

    try {
      const result = await handler(request);
      data.value = result;
      status.value = 'success';
      return result;
    } catch (err) {
      error.value = err;
      status.value = 'error';
      return undefined;
    } finally {
      isLoading.value = status.value === 'pending';
    }
  });

  const reset = $(() => {
    status.value = 'idle';
    data.value = null;
    error.value = null;
    isLoading.value = false;
    lastRequest.value = null;
  });

  return {
    status,
    data,
    error,
    isLoading,
    lastRequest,
    send,
    reset,
    get ctx() { return ctxRef.value!; },
  };
}
