// packages/qwik/src/useAskableUserSource.ts
import { $ } from '@builder.io/qwik';
import type { QRL, SyncQRL } from '@builder.io/qwik';
import { createAskableUserSource } from '@askable-ui/core';
import type { AskableCreateUserSourceOptions, AskableUserProfile } from '@askable-ui/core';
export type { AskableUserProfile } from '@askable-ui/core';
import {
  useAskableSource,
  type AskableContextSourceFactory,
  type UseAskableSourceOptions,
  type UseAskableSourceResult,
} from './useAskableSource.js';

type UserDescription = Extract<
  NonNullable<AskableCreateUserSourceOptions['describe']>,
  (...args: never[]) => unknown
>;

export interface UseAskableUserSourceOptions
  extends UseAskableSourceOptions,
    Omit<AskableCreateUserSourceOptions, 'describe' | 'getUser' | 'sanitize'> {
  id?: string;
  describe?: string | QRL<UserDescription>;
  getUser: QRL<() => AskableUserProfile | null | undefined | Promise<AskableUserProfile | null | undefined>>;
  sanitize?: SyncQRL<NonNullable<AskableCreateUserSourceOptions['sanitize']>>;
  /** Advanced resume-safe factory for custom identity integrations. */
  source$?: AskableContextSourceFactory;
}

export interface UseAskableUserSourceResult extends UseAskableSourceResult {}

/** Registers a user profile source with resume-safe data providers. */
export function useAskableUserSource(
  options: UseAskableUserSourceOptions,
): UseAskableUserSourceResult {
  const {
    id = 'user',
    enabled,
    ctx,
    ctx$,
    name,
    events,
    viewport,
    textExtractor,
    sanitizeMeta,
    sanitizeText,
    sanitizeSource,
    maxHistory,
    describe,
    getUser,
    sanitize,
    source$,
    ...sourceOptions
  } = options;

  const defaultSourceFactory = $(async () => {
    const [resolvedDescribe, resolvedGetUser, resolvedSanitize] = await Promise.all([
      typeof describe === 'string' ? describe : describe?.resolve(),
      getUser.resolve(),
      sanitize?.resolve(),
    ]);
    return createAskableUserSource({
      ...sourceOptions,
      describe: resolvedDescribe,
      getUser: resolvedGetUser,
      sanitize: resolvedSanitize,
    });
  });
  return useAskableSource(
    id,
    source$ ?? defaultSourceFactory,
    {
      enabled, ctx, ctx$, name, events, viewport, textExtractor,
      sanitizeMeta, sanitizeText, sanitizeSource, maxHistory,
    },
  );
}

// packages/solid/src/useAskableUserSource.ts
import { createEffect } from 'solid-js';
import { createAskableUserSource } from '@askable-ui/core';
import type { AskableCreateUserSourceOptions, AskableUserProfile } from '@askable-ui/core';
import { useAskableSource, type UseAskableSourceOptions, type UseAskableSourceResult } from './useAskableSource.js';

export type { AskableUserProfile };

export interface UseAskableUserSourceOptions
  extends UseAskableSourceOptions,
    Omit<AskableCreateUserSourceOptions, 'getUser'> {
  /** Source registration id. Defaults to "user". */
  id?: string;
  /**
   * Accessor returning the current user profile.
   * Return null to represent "not logged in".
   */
  user?: () => AskableUserProfile | null | undefined;
}

export type UseAskableUserSourceResult = UseAskableSourceResult;

/**
 * SolidJS primitive that registers a user profile source so AI assistants can
 * personalise responses — addressing users by name, respecting their role
 * and plan, and adapting to their locale.
 *
 * ```tsx
 * const [user] = createSignal<AskableUserProfile | null>(null);
 * useAskableUserSource({ user });
 *
 * // With Clerk Solid SDK
 * const { user } = useUser();
 * useAskableUserSource({
 *   user: () => user() ? { name: user()!.fullName, role: user()!.publicMetadata.role } : null,
 * });
 * ```
 */
export function useAskableUserSource(
  options: UseAskableUserSourceOptions = {},
): UseAskableUserSourceResult {
  const {
    id = 'user',
    user,
    describe,
    kind,
    omitFields,
    sanitize,
    enabled,
    ctx,
    name,
    events,
  } = options;

  const userSource = createAskableUserSource({
    describe,
    kind,
    omitFields,
    sanitize,
    getUser: () => user?.() ?? null,
  });

  const result = useAskableSource(id, userSource, { enabled, ctx, name, events });

  if (user) {
    createEffect(() => {
      user();
      result.notifyChanged();
    });
  }

  return result;
}
