// packages/qwik/src/useAskableNavigationSource.ts
import { $ } from '@builder.io/qwik';
import type { SyncQRL } from '@builder.io/qwik';
import { createAskableNavigationSource } from '@askable-ui/core';
import type { AskableCreateNavigationSourceOptions } from '@askable-ui/core';
export type { AskableNavigationEntry } from '@askable-ui/core';
import {
  useAskableSource,
  type AskableContextSourceFactory,
  type UseAskableSourceOptions,
  type UseAskableSourceResult,
} from './useAskableSource.js';

export interface UseAskableNavigationSourceOptions
  extends UseAskableSourceOptions,
    Omit<
      AskableCreateNavigationSourceOptions,
      'getPath' | 'getTitle' | 'getParams' | 'describe'
    > {
  id?: string;
  getPath?: SyncQRL<NonNullable<AskableCreateNavigationSourceOptions['getPath']>>;
  getTitle?: SyncQRL<NonNullable<AskableCreateNavigationSourceOptions['getTitle']>>;
  getParams?: SyncQRL<NonNullable<AskableCreateNavigationSourceOptions['getParams']>>;
  describe?: SyncQRL<NonNullable<AskableCreateNavigationSourceOptions['describe']>>;
  /** Advanced resume-safe factory for router state that cannot use `sync$`. */
  source$?: AskableContextSourceFactory;
}

export interface UseAskableNavigationSourceResult extends UseAskableSourceResult {}

/** Registers a navigation source with resume-safe callbacks and history. */
export function useAskableNavigationSource(
  options: UseAskableNavigationSourceOptions = {},
): UseAskableNavigationSourceResult {
  const {
    id = 'navigation',
    enabled,
    ctx,
    ctx$,
    name,
    events,
    viewport,
    textExtractor,
    sanitizeMeta,
    sanitizeText,
    sanitizeSource,
    maxHistory,
    getPath,
    getTitle,
    getParams,
    describe,
    source$,
    ...sourceOptions
  } = options;

  const defaultSourceFactory = $(async () => {
    const [resolvedPath, resolvedTitle, resolvedParams, resolvedDescribe] = await Promise.all([
      getPath?.resolve(),
      getTitle?.resolve(),
      getParams?.resolve(),
      describe?.resolve(),
    ]);
    return createAskableNavigationSource({
      ...sourceOptions,
      getPath: resolvedPath,
      getTitle: resolvedTitle,
      getParams: resolvedParams,
      describe: resolvedDescribe,
    });
  });
  return useAskableSource(
    id,
    source$ ?? defaultSourceFactory,
    {
      enabled, ctx, ctx$, name, events, viewport, textExtractor,
      sanitizeMeta, sanitizeText, sanitizeSource, maxHistory,
    },
  );
}

// packages/solid/src/useAskableNavigationSource.ts
import { createEffect } from 'solid-js';
import { createAskableNavigationSource } from '@askable-ui/core';
import type {
  AskableCreateNavigationSourceOptions,
  AskableNavigationEntry,
} from '@askable-ui/core';
import { useAskableSource, type UseAskableSourceOptions, type UseAskableSourceResult } from './useAskableSource.js';

export type { AskableNavigationEntry };

export interface UseAskableNavigationSourceOptions
  extends UseAskableSourceOptions,
    AskableCreateNavigationSourceOptions {
  /** Source registration id. Defaults to "navigation". */
  id?: string;
  /**
   * Accessor returning the current path string. When provided, the hook tracks
   * this accessor and calls `notifyChanged()` automatically on change.
   *
   * @example () => location().pathname  // SolidJS Router's useLocation()
   */
  pathname?: () => string;
}

export type UseAskableNavigationSourceResult = UseAskableSourceResult;

/**
 * SolidJS primitive that registers a navigation source so AI assistants can
 * understand where the user is in the application.
 *
 * @example
 * ```tsx
 * // SolidJS Router — auto-notifies on route changes
 * const location = useLocation();
 * useAskableNavigationSource({
 *   pathname: () => location.pathname,
 *   getPath: () => location.pathname + location.search,
 * });
 * ```
 */
export function useAskableNavigationSource(
  options: UseAskableNavigationSourceOptions = {},
): UseAskableNavigationSourceResult {
  const {
    id = 'navigation',
    pathname,
    getPath,
    getTitle,
    getParams,
    maxHistory,
    describe,
    kind,
    enabled,
    ctx,
    name,
    events,
  } = options;

  const source = createAskableNavigationSource({ getPath, getTitle, getParams, maxHistory, describe, kind });
  const result = useAskableSource(id, source, { enabled, ctx, name, events });

  if (pathname) {
    createEffect(() => {
      pathname();
      result.notifyChanged();
    });
  }

  return result;
}
